import { INGREDIENTS } from '@/data/ingredients'

/**
 * The remote source names ingredients in free text ("Free-range Egg", "Plain
 * Flour", "Spring Onions"). This maps those onto catalogue ids so a remote
 * recipe can be matched against a pantry the same way a local one is.
 */
const SYNONYMS: Record<string, string> = {
  egg: 'egg',
  eggs: 'egg',
  'free-range egg': 'egg',
  'egg yolks': 'egg',
  'egg whites': 'egg',
  flour: 'flour',
  'plain flour': 'flour',
  'all purpose flour': 'flour',
  'self-raising flour': 'flour',
  milk: 'milk',
  'whole milk': 'milk',
  butter: 'butter',
  'unsalted butter': 'butter',
  'olive oil': 'olive-oil',
  'vegetable oil': 'olive-oil',
  'sunflower oil': 'olive-oil',
  oil: 'olive-oil',
  onion: 'onion',
  onions: 'onion',
  'red onion': 'onion',
  'red onions': 'onion',
  shallots: 'onion',
  garlic: 'garlic',
  'garlic clove': 'garlic',
  'garlic cloves': 'garlic',
  'minced garlic': 'garlic',
  carrots: 'carrot',
  carrot: 'carrot',
  tomatoes: 'tomato',
  tomato: 'tomato',
  'cherry tomatoes': 'tomato',
  'chopped tomatoes': 'canned-tomatoes',
  'canned tomatoes': 'canned-tomatoes',
  'tinned tomatoes': 'canned-tomatoes',
  'tomato puree': 'canned-tomatoes',
  'red pepper': 'bell-pepper',
  'green pepper': 'bell-pepper',
  'yellow pepper': 'bell-pepper',
  'bell pepper': 'bell-pepper',
  peppers: 'bell-pepper',
  courgettes: 'courgette',
  courgette: 'courgette',
  zucchini: 'courgette',
  aubergine: 'aubergine',
  eggplant: 'aubergine',
  spinach: 'spinach',
  mushrooms: 'mushroom',
  mushroom: 'mushroom',
  cabbage: 'cabbage',
  cucumber: 'cucumber',
  lemon: 'lemon',
  'lemon juice': 'lemon',
  'lemons juice': 'lemon',
  lime: 'lime',
  'lime juice': 'lime',
  banana: 'banana',
  bananas: 'banana',
  apples: 'apple',
  apple: 'apple',
  'spring onions': 'spring-onion',
  'spring onion': 'spring-onion',
  'green onions': 'spring-onion',
  'sea salt': 'salt',
  salt: 'salt',
  pepper: 'pepper',
  'black pepper': 'pepper',
  'ground pepper': 'pepper',
  paprika: 'paprika',
  'smoked paprika': 'paprika',
  cumin: 'cumin',
  'ground cumin': 'cumin',
  'curry powder': 'curry-powder',
  'chilli powder': 'chilli-flakes',
  'chili powder': 'chilli-flakes',
  'red chilli flakes': 'chilli-flakes',
  'chilli flakes': 'chilli-flakes',
  oregano: 'oregano',
  'dried oregano': 'oregano',
  basil: 'basil',
  'fresh basil': 'basil',
  parsley: 'parsley',
  'fresh parsley': 'parsley',
  coriander: 'coriander',
  cilantro: 'coriander',
  ginger: 'ginger',
  'fresh ginger': 'ginger',
  'ground ginger': 'ginger',
  cinnamon: 'cinnamon',
  'ground cinnamon': 'cinnamon',
  sugar: 'sugar',
  'caster sugar': 'sugar',
  'brown sugar': 'sugar',
  honey: 'honey',
  'soy sauce': 'soy-sauce',
  'white wine vinegar': 'vinegar',
  'red wine vinegar': 'vinegar',
  vinegar: 'vinegar',
  'baking powder': 'baking-powder',
  'peanut butter': 'peanut-butter',
  rice: 'rice',
  'basmati rice': 'rice',
  'arborio rice': 'rice',
  pasta: 'pasta',
  spaghetti: 'pasta',
  macaroni: 'pasta',
  penne: 'pasta',
  noodles: 'pasta',
  bread: 'bread',
  'bread rolls': 'bread',
  potatoes: 'potato',
  potato: 'potato',
  oats: 'oats',
  'rolled oats': 'oats',
  'porridge oats': 'oats',
  chickpeas: 'chickpeas',
  'red lentils': 'lentils',
  lentils: 'lentils',
  'coconut milk': 'coconut-milk',
  'chicken stock': 'stock',
  'vegetable stock': 'stock',
  'beef stock': 'stock',
  'stock cube': 'stock',
  yoghurt: 'yoghurt',
  yogurt: 'yoghurt',
  'greek yogurt': 'yoghurt',
  'cheddar cheese': 'cheddar',
  cheddar: 'cheddar',
  parmesan: 'parmesan',
  'parmesan cheese': 'parmesan',
  'feta cheese': 'feta',
  feta: 'feta',
  cream: 'cream',
  'double cream': 'cream',
  'heavy cream': 'cream',
  'chicken thighs': 'chicken-thigh',
  'chicken thigh': 'chicken-thigh',
  'chicken breast': 'chicken-breast',
  'chicken breasts': 'chicken-breast',
  chicken: 'chicken-breast',
  'minced beef': 'minced-beef',
  'ground beef': 'minced-beef',
  'beef mince': 'minced-beef',
  bacon: 'bacon',
  'streaky bacon': 'bacon',
  'white fish': 'white-fish',
  cod: 'white-fish',
  haddock: 'white-fish',
  tuna: 'tuna',
  tofu: 'tofu',
  prawns: 'prawns',
  shrimp: 'prawns',
  walnuts: 'walnuts',
  raisins: 'raisins',
  olives: 'olives',
  'sesame seed': 'sesame-seeds',
  'sesame seeds': 'sesame-seeds',
  'dark chocolate': 'dark-chocolate',
  chocolate: 'dark-chocolate',
}

/** Catalogue names themselves are always valid input. */
const BY_NAME = new Map(INGREDIENTS.map((i) => [i.name.toLowerCase(), i.id]))

export function resolveIngredientId(raw: string): string | null {
  const key = raw.trim().toLowerCase().replace(/\s+/g, ' ')
  if (!key) return null
  return SYNONYMS[key] ?? BY_NAME.get(key) ?? null
}
